services:
  db:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    platform: linux/amd64
    ports:
      - "5432:5432"
    environment:
      - DATABASE_URL=$DATABASE_URL
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    volumes:
      - "db:/var/lib/postgresql/data"

  app:
    build: .
    depends_on:
      - db
    container_name: brevly-server
    restart: unless-stopped
    ports:
      - 3000:3333
    environment:
      - CLOUDFLARE_ACCOUNT_ID=$CLOUDFLARE_ACCOUNT_ID
      - CLOUDFLARE_ACCESS_KEY_ID=$CLOUDFLARE_ACCESS_KEY_ID
      - CLOUDFLARE_SECRET_ACCESS_KEY_ID=$CLOUDFLARE_SECRET_ACCESS_KEY_ID
      - CLOUDFLARE_BUCKET=$CLOUDFLARE_BUCKET
      - CLOUDFLARE_PUBLIC_URL=$CLOUDFLARE_PUBLIC_URL

volumes:
  db:
    