services:
  db:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=brevly-server
    volumes:
      - "db:/var/lib/postgresql/data"

  app:
    build: .
    container_name: brevly-server
    ports:
      - 3000:3333
    environment:
      - DATABASE_URL=postgresql://example.com
      - CLOUDFLARE_ACCOUNT_ID=#
      - CLOUDFLARE_ACCESS_KEY_ID=#
      - CLOUDFLARE_SECRET_ACCESS_KEY_ID=#
      - CLOUDFLARE_BUCKET=#
      - CLOUDFLARE_PUBLIC_URL=https://example.com

volumes:
  db:
    